server.port=8202
spring.application.name=resilient-gateway

spring.cloud.gateway.routes[0].id=resilient_route
spring.cloud.gateway.routes[0].uri=http://localhost:8091
spring.cloud.gateway.routes[0].predicates[0]=Path=/resilient/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=exampleCircuitBreaker

resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
